# Generated by Django 4.1.7 on 2023-03-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='default/default.jpg', upload_to='Blog Image/'),
        ),
    ]
